### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by JonyBepary** [bharadwaj-raju/TextSuggest#26]
When I Run Text Suggest Following Issues Prevent It To Launch 

```
$ textsuggest
awk: line 0: regular expression compile failed (missing operand)
(+|\()
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 196, in <module>
    current_word = sp.check_output(['xsel'])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
```

**Comment by bharadwaj-raju** [comment]
Have you installed `xsel`? It is listed as a requirement in the README.
