### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by JonyBepary** [bharadwaj-raju/TextSuggest#27]
acording to issue no. #26  after installing xsel
When I Run Text Suggest Following Issues Prevent It To Launch 

```
$ textsuggest
awk: line 0: regular expression compile failed (missing operand)
(+|\()
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 374, in <module>
    main()
  File "/usr/bin/textsuggest", line 351, in main
    words_list = get_suggestions(current_word, dict_files=get_dictionaries())
  File "/usr/bin/textsuggest", line 214, in get_dictionaries
    for file in os.listdir(os.path.join(base_dict_dir, lang)):
PermissionError: [Errno 13] Permission denied: '/usr/share/textsuggest/dictionaries/English'

```

**Comment by bharadwaj-raju** [comment]
Of course, try checking the permissions.

**Comment by bharadwaj-raju** [comment]
```
chmod -R +r /usr/share/textsuggest
```

**Comment by JonyBepary** [comment]
no good same problem

**Comment by JonyBepary** [comment]
but one thing when run `sudo textsuggest` it's work like a charm !!! . But according to the docs it should be run without root permission. Right ?

**Comment by bharadwaj-raju** [comment]
Yes, it is a permissions problem. Verify that `/usr/share/textsuggest` is world-readable.

Try: `sudo chmod -R a+r /usr/share/textsuggest`

**Comment by JonyBepary** [comment]
yeah problem solved. Thank a lot !
