### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by amitguptagwl** [bharadwaj-raju/TextSuggest#56]
I'm seeing this error while running on Ubuntu 17.10

```
xdo_get_focused_window_sane failed (code=1)
xdo_focus_window reported an error
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 542, in <module>
    main()
  File "/usr/bin/textsuggest", line 454, in main
    focused_window_id = get_focused_window_id()
  File "/usr/bin/textsuggest", line 123, in get_focused_window_id
    return get_cmd_out(['xdotool', 'getwindowfocus']).strip()
  File "/usr/bin/textsuggest", line 65, in get_cmd_out
    return sp.check_output(program, shell=run_in_shell).decode('utf-8').rstrip('\n').replace('\\n', '\n')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xdotool', 'getwindowfocus']' returned non-zero exit status 1.
```

**Comment by bharadwaj-raju** [comment]
This is an issue with the target application window and/or X11 or xdotool.

Unfortunately this cannot this be fixed in TextSuggest.
