### ISSUE TITLE
textsuggest: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by textsuggest)

### ISSUE THREAD

**Issue by asongdon** [bharadwaj-raju/TextSuggest#60]
Hi,
I got the following msg when I try to run textsuggest
`textsuggest: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by textsuggest)`

How can I solve this?

**Comment by bharadwaj-raju** [comment]
Are you running a 32-bit OS?

**Comment by bharadwaj-raju** [comment]
Please upgrade to Qt 5.10, or, if you can, compile it yourself (it's actually very easy) using the instructions in INSTALL.md file.

Also, please mention your distro and distro version...

**Comment by bharadwaj-raju** [comment]
Please download the latest release again, and this time, run `sudo sh auto-install.sh`...

**Comment by asongdon** [comment]
Got the following:

```Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libdbus-c++-1-0' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-bin' for regex 'dbus-c+'
Note, selecting 'python-dbus-common' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dbg' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dev' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-doc' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-1-0v5' for regex 'dbus-c+'
E: Unable to locate package dbus-python
```

**Comment by asongdon** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by bharadwaj-raju** [comment]
Just uploaded a fixed script. Please try again.

**Comment by asongdon** [comment]
Got a lot more info here but still stuck I guess.

```Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libdbus-c++-1-0' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-bin' for regex 'dbus-c+'
Note, selecting 'python-dbus-common' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dbg' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dev' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-doc' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-1-0v5' for regex 'dbus-c+'
build-essential is already the newest version (12.4ubuntu1).
python-dbus is already the newest version (1.2.6-1).
qt5-qmake is already the newest version (5.9.5+dfsg-0ubuntu1).
qt5-qmake set to manually installed.
qtbase5-dev is already the newest version (5.9.5+dfsg-0ubuntu1).
libdbus-c++-1-0v5 is already the newest version (0.9.0-8.1).
libdbus-c++-bin is already the newest version (0.9.0-8.1).
libdbus-c++-dbg is already the newest version (0.9.0-8.1).
libdbus-c++-dev is already the newest version (0.9.0-8.1).
libdbus-c++-doc is already the newest version (0.9.0-8.1).
qt5-default is already the newest version (5.9.5+dfsg-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xclip is already the newest version (0.12+svn84-4build1).
xdotool is already the newest version (1:3.20160805.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-e Building...
Info: creating stash file /home/art/Downloads/TextSuggest-3.0.0/ui/.qmake.stash
Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dbus-1', required by 'dbus-c++-1', not found
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o EventCatcherEntry.o EventCatcherEntry.cpp
EventCatcherEntry.cpp: In constructor ‘EventCatcherEntry::EventCatcherEntry(QWidget*)’:
EventCatcherEntry.cpp:3:48: warning: unused parameter ‘parent’ [-Wunused-parameter]
 EventCatcherEntry::EventCatcherEntry(QWidget * parent) {}
                                                ^~~~~~
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o textsuggest-ui.o textsuggest-ui.cpp
textsuggest-ui.cpp:5:10: fatal error: dbus-c++/dbus.h: No such file or directory
 #include <dbus-c++/dbus.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:404: recipe for target 'textsuggest-ui.o' failed
make: *** [textsuggest-ui.o] Error 1
```

**Comment by bharadwaj-raju** [comment]
Fixed now. Please try again with latest release.

**Comment by asongdon** [comment]
Thx for a very quick response, but seem not to work for me

``` 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libdbus-c++-1-0' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-bin' for regex 'dbus-c+'
Note, selecting 'python-dbus-common' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dbg' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-dev' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-doc' for regex 'dbus-c+'
Note, selecting 'libdbus-c++-1-0v5' for regex 'dbus-c+'
build-essential is already the newest version (12.4ubuntu1).
python-dbus is already the newest version (1.2.6-1).
qt5-qmake is already the newest version (5.9.5+dfsg-0ubuntu1).
qtbase5-dev is already the newest version (5.9.5+dfsg-0ubuntu1).
libdbus-c++-1-0v5 is already the newest version (0.9.0-8.1).
libdbus-c++-bin is already the newest version (0.9.0-8.1).
libdbus-c++-dbg is already the newest version (0.9.0-8.1).
libdbus-c++-dev is already the newest version (0.9.0-8.1).
libdbus-c++-doc is already the newest version (0.9.0-8.1).
qt5-default is already the newest version (5.9.5+dfsg-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xclip is already the newest version (0.12+svn84-4build1).
xdotool is already the newest version (1:3.20160805.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-e Building...
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/dbus-c++-1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o EventCatcherEntry.o EventCatcherEntry.cpp
EventCatcherEntry.cpp: In constructor ‘EventCatcherEntry::EventCatcherEntry(QWidget*)’:
EventCatcherEntry.cpp:3:48: warning: unused parameter ‘parent’ [-Wunused-parameter]
 EventCatcherEntry::EventCatcherEntry(QWidget * parent) {}
                                                ^~~~~~
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/dbus-c++-1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o textsuggest-ui.o textsuggest-ui.cpp
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/dbus-c++-1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o TextSuggestApp.o TextSuggestApp.cpp
TextSuggestApp.cpp: In member function ‘void TextSuggestApp::textEdited(const QString&)’:
TextSuggestApp.cpp:135:48: warning: unused parameter ‘text’ [-Wunused-parameter]
 void TextSuggestApp::textEdited(const QString &text) {
                                                ^~~~
In file included from TextSuggestApp.hpp:9:0,
                 from TextSuggestApp.cpp:1:
TextSuggestServerIFace.hpp: At global scope:
TextSuggestServerIFace.hpp:8:21: warning: ‘OBJECT_PATH’ defined but not used [-Wunused-variable]
 static const char * OBJECT_PATH = "/org/textsuggest/server";
                     ^~~~~~~~~~~
TextSuggestServerIFace.hpp:7:21: warning: ‘SERVICE_NAME’ defined but not used [-Wunused-variable]
 static const char * SERVICE_NAME = "org.textsuggest.server";
                     ^~~~~~~~~~~~
g++ -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
/usr/lib/qt5/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/art/Downloads/TextSuggest-3.0.0/ui -I/home/art/Downloads/TextSuggest-3.0.0/ui -I/usr/include/dbus-c++-1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include EventCatcherEntry.hpp -o moc_EventCatcherEntry.cpp
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/dbus-c++-1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_EventCatcherEntry.o moc_EventCatcherEntry.cpp
/usr/lib/qt5/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/art/Downloads/TextSuggest-3.0.0/ui -I/home/art/Downloads/TextSuggest-3.0.0/ui -I/usr/include/dbus-c++-1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include TextSuggestApp.hpp -o moc_TextSuggestApp.cpp
g++ -c -pipe -ggdb3 -fstack-protector-all -fno-omit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/dbus-c++-1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_TextSuggestApp.o moc_TextSuggestApp.cpp
In file included from TextSuggestApp.hpp:9:0,
                 from moc_TextSuggestApp.cpp:9:
TextSuggestServerIFace.hpp:8:21: warning: ‘OBJECT_PATH’ defined but not used [-Wunused-variable]
 static const char * OBJECT_PATH = "/org/textsuggest/server";
                     ^~~~~~~~~~~
TextSuggestServerIFace.hpp:7:21: warning: ‘SERVICE_NAME’ defined but not used [-Wunused-variable]
 static const char * SERVICE_NAME = "org.textsuggest.server";
                     ^~~~~~~~~~~~
g++ -Wl,-O1 -o textsuggest EventCatcherEntry.o textsuggest-ui.o TextSuggestApp.o moc_EventCatcherEntry.o moc_TextSuggestApp.o   -ldbus-c++-1 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
mv: cannot move 'textsuggest' to '../bin/textsuggest': No such file or directory
```

**Comment by bharadwaj-raju** [comment]
Try again with latest release, please.

I'm confident it will work this time.

**Comment by bharadwaj-raju** [comment]
Also, thank you. Without this issue, I wouldn't have been able to resolve the bugs in the new install procedure...

**Comment by asongdon** [comment]
Installation works great! Now when I try to start the textsuggest-server I got this, how do I solve that?

```art@art-ubuntu:~/Downloads/TextSuggest-3.0.0$ textsuggest-server
Started DBus service at org.textsuggest.server, PID 26605
Traceback (most recent call last):
  File "/usr/bin/textsuggest-server", line 515, in <module>
    main()
  File "/usr/bin/textsuggest-server", line 511, in main
    srv.run()
  File "/usr/bin/textsuggest-server", line 162, in run
    with open(dict_file[1]) as f:
PermissionError: [Errno 13] Permission denied: '/usr/share/textsuggest/dictionaries/English.txt'
```

**Comment by bharadwaj-raju** [comment]
Does this command fix it?

    $ sudo chmod a+rwx /usr/share/textsuggest

**Comment by asongdon** [comment]
I ran
`sudo chmod a+rwx /usr/share/textsuggest`
`sudo chmod a+rwx /usr/share/textsuggest/dictionaries`
`sudo chmod a+rwx /usr/share/textsuggest/dictionaries/English.txt`

and got,
```
Started DBus service at org.textsuggest.server, PID 27235
Failed to open custom words file, or custom words file was empty.
```
So this means it work now? and step is to create shortcut and so on base on your document?

**Comment by bharadwaj-raju** [comment]
Yes, it's successful!

I'd recommend going through the "Features" listed in the Readme.

And again, thank you for reporting this bug.

**Comment by asongdon** [comment]
Awesome, thank you too!
